services:
  - type: web
    name: trackfade
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_SECRET_KEY
        value: f6011816e17dab9e43292ca7f997bf66226f464066a7d23d
      - key: SESSION_TYPE
        value: filesystem
      - key: SESSION_COOKIE_SECURE
        value: 'True'
      - key: SESSION_COOKIE_SAMESITE
        value: Lax
      - key: SPOTIFY_CLIENT_ID
        value: 0420161b17bd47feb363bc86d154f9f1
      - key: SPOTIFY_CLIENT_SECRET
        value: 340df76e729148998df0114cfb334849
      - key: SPOTIFY_REDIRECT_URI
        value: https://trackfade.onrender.com/callback
      - key: APPLE_TEAM_ID
        value: B9P7BYTB4S
      - key: APPLE_KEY_ID
        value: X3MF4GG832
      - key: APPLE_PRIVATE_KEY
        value: |
          -----BEGIN PRIVATE KEY-----
          MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgCV0oJ8VZEYB34Qyx
          MPfuOuG9dhe165x8Oq5azVB/kKqgCgYIKoZIzj0DAQehRANCAASNotmRHJjEQHDR
          b90U0kXp/EVHn0XHe4JdaEGBkLkdL/hCF/TnicmNXw0tpenJ3+2XjN4E4Up/Phl0
          XyYhWhn7
          -----END PRIVATE KEY-----
